In [1]:
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
import os.path
import csv
from pathlib import Path

In [2]:
ticker = 'FB'
test_df = pd.read_pickle(f"./pickle_stock_data2/{ticker}.pickle")

In [3]:
test_df

                  Open        High         Low   Adj Close     Volume
Date
2012-05-18   42.049999   45.000000   38.000000   38.230000  573576400
2012-05-21   36.529999   36.660000   33.000000   34.029999  168192700
2012-05-22   32.610001   33.590000   30.940001   31.000000  101786600
2012-05-23   31.370001   32.500000   31.360001   32.000000   73600000
2012-05-24   32.950001   33.209999   31.770000   33.029999   50237200
2012-05-25   32.900002   32.950001   31.110001   31.910000   37149800
2012-05-29   31.480000   31.690001   28.650000   28.840000   78063400
2012-05-30   28.700001   29.549999   27.860001   28.190001   57267900
2012-05-31   28.549999   29.670000   26.830000   29.600000  111639200
2012-06-01   28.889999   29.150000   27.389999   27.719999   41855500
2012-06-04   27.200001   27.650000   26.440001   26.900000   35230300
2012-06-05   26.700001   27.760000   25.750000   25.870001   42473400
2012-06-06   26.070000   27.170000   25.520000   26.809999   61489200
2012-06-07   27.000000   27.350000   26.150000   26.309999   26159500
2012-06-08   26.549999   27.760000   26.440001   27.100000   38034000
2012-06-11   27.180000   28.070000   26.840000   27.010000   28219600
2012-06-12   27.480000   27.770000   26.959999   27.400000   15816800
2012-06-13   27.660000   28.100000   27.100000   27.270000   17102800
2012-06-14   27.650000   28.320000   27.379999   28.290001   16855000
2012-06-15   28.510000   30.100000   28.350000   30.010000   43563800
2012-06-18   29.959999   32.080002   29.410000   31.410000   42978900
2012-06-19   31.540001   32.180000   30.700001   31.910000   30849000
2012-06-20   31.920000   31.930000   31.150000   31.600000   15553600
2012-06-21   31.670000   32.500000   31.510000   31.840000   21875300
2012-06-22   32.410000   33.450001   32.060001   33.049999   74834000
2012-06-25   32.860001   33.020000   31.549999   32.060001   24352900
2012-06-26   32.689999   33.439999   32.500000   33.099998   24858700
2012-06-27   32.459999   32.900002   31.900000   32.230000   28568000
2012-06-28   31.959999   32.189999   30.900000   31.360001   17713300
2012-06-29   31.920000   31.990000   30.760000   31.100000   19526900
...                ...         ...         ...         ...        ...
2019-08-09  190.000000  190.979996  187.119995  187.850006   11058800
2019-08-12  186.850006  187.589996  184.460007  185.369995   10936300
2019-08-13  185.520004  191.380005  185.369995  188.449997   13577000
2019-08-14  185.800003  185.990005  179.309998  179.710007   18903700
2019-08-15  180.949997  183.199997  180.029999  182.589996   12925900
2019-08-16  183.750000  185.100006  182.360001  183.699997   12654600
2019-08-19  186.009995  187.500000  184.850006  186.169998    9691200
2019-08-20  185.449997  186.000000  182.389999  183.809998   10083400
2019-08-21  185.000000  185.899994  183.139999  183.550003    8398200
2019-08-22  183.429993  184.110001  179.910004  182.039993   10821400
2019-08-23  180.839996  183.130005  176.660004  177.750000   17323400
2019-08-26  179.399994  180.500000  178.240005  180.360001    8773600
2019-08-27  181.929993  184.039993  181.009995  181.300003   14399600
2019-08-28  180.529999  181.949997  178.919998  181.759995    9386100
2019-08-29  183.770004  186.080002  183.470001  185.570007   10128700
2019-08-30  186.779999  186.800003  183.460007  185.669998   10774500
2019-09-03  184.000000  185.669998  182.110001  182.389999    9779400
2019-09-04  184.649994  187.750000  183.889999  187.139999   11308000
2019-09-05  188.529999  191.360001  187.940002  190.899994   13876700
2019-09-06  190.210007  190.210007  186.350006  187.490005   15226800
2019-09-09  187.729996  188.979996  185.850006  188.759995   14722400
2019-09-10  187.440002  188.100006  184.550003  186.169998   15455900
2019-09-11  186.460007  189.440002  186.080002  188.490005   11761700
2019-09-12  189.860001  190.929993  187.229996  187.470001   11419800
2019-09-13  187.330002  187.970001  186.539993  187.190002   11441100
2019-09-16  186.929993  187.789993  185.770004  186.220001    8444800
2019-09-17  186.660004  188.320007  185.539993  188.080002    9671100
2019-09-18  188.089996  189.080002  186.009995  188.139999    9681900
2019-09-19  188.660004  191.100006  188.149994  190.139999   10392700
2019-09-20  190.660004  193.100006  188.119995  189.929993   19934200

[1847 rows x 5 columns]